apiVersion: v1
kind: Service
metadata:
  labels:
    app: application
  name: application-svc
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: {{ .Values.application.service.nodeport }}
  selector:
    app: application
  type: NodePort